apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: example
spec:
  hostCollectors:
    - hostOS: {}
    - diskUsage:
        collectorName: root-disk
        path: /
  hostAnalyzers:
    - hostOS:
        outcomes:
          - pass:
              when: "centos = 7"
              message: "CentOS 7 is supported"
          - pass:
              when: "centos = 8"
              message: "CentOS 8 is supported"
          - fail:
              when: "ubuntu = 16.04"
              message: "Ubuntu 16.04 is not supported"
          - pass:
              when: "ubuntu = 18.04"
              message: "Ubuntu 18.04 is supported"
          - pass:
              when: "ubuntu = 20.04"
              message: "Ubuntu 20.04 is supported"
    - diskUsage:
        checkName: "Root Disk at least 50Gi"
        collectorName: root-disk
        outcomes:
          - fail:
              when: "total < 50Gi"
              message: The disk containing directory / has less than 30Gi of total space
          - fail:
              when: "used/total > 80%"
              message: The disk containing directory / is more than 80% full
          - warn:
              when: "used/total > 60%"
              message: The disk containing directory / is more than 60% full
          - warn:
              when: "available < 10Gi"
              message: The disk containing directory / has less than 10Gi of disk space available
          - pass:
              message: The disk containing directory / has at least 30Gi of total space, has at least 10Gi of disk space available, and is less than 60% full